# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GODING-EO' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'DropDown'

  # Pods for GODING-EO

  target 'GODING-EOTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GODING-EOUITests' do
    # Pods for testing
  end

end
